#!/bin/bash

# Get script name
SCRIPT=$(basename "$0")

# First param is docker container
CONTAINER=$1

# Default configuration
PACKAGE_PATH="/usr/lib/python3/dist-packages/"

# Custom configuration
FILE_PATH="${PACKAGE_PATH}odoo/addons/hr_holidays/models/hr_leave.py"
FIND="'name': meeting_name,"
REPLACE="'name': meeting_name.replace('on Time Off ', holiday.holiday_status_id.name),"

# Get filename
FILE=`basename "$FILE_PATH"`

# Copy from docker
docker cp "$CONTAINER":"$FILE_PATH" .

# Find and replace
sed -i'' "s/$FIND/$REPLACE/g" $FILE

# Copy back to docker
docker cp $FILE "$CONTAINER":"$FILE_PATH"

# Remove file
rm -f $FILE

# Register patch installation
echo "Patch $SCRIPT applied."
touch "/etc/odoo/${SCRIPT}_${CONTAINER}_installed"
