#!/usr/bin/env bash
set -e

script=$(basename "$0")
version="1.0.0"

help() {
    echo
    echo "$script"
    echo
    echo 'Description: Reload Nginx config in container.'
    echo "Syntax: $script [-t|-o|help]"
    echo 'Example: $script -c nginx01'
    echo 'options:'
    echo '  -c    Name of the container.'
    echo "  -V    Show $script version."
    echo '  help  Show $script manual.'
    echo
}

if [[ "$1" == 'help' ]]; then
    help
    exit
fi

# Process params
while getopts ":c::V" opt; do
  case $opt in
    c) container="$OPTARG"
    ;;
    V) echo "$script version $version"
    exit 0
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    help
    exit 1;;
  esac
done

# Verify variables
[[ -z "$container" ]] && { echo 'Parameter -c|container is empty' ; exit 1; }

echo "Reload Nginx config on $container"
docker exec "$container" /usr/sbin/nginx -s reload