#!/bin/bash
set -e

# Get script name
SCRIPT=$(basename "$0")
VERSION="1.0.0"

# Display Help
Help() {
    echo
    echo "$SCRIPT"
    echo
    echo "Description: Show public facing ip of server."
    echo "Syntax: $SCRIPT [-V|help]"
    echo "Example: $SCRIPT"
    echo "options:"
    echo "  -c    Docker container. Defaults to 'odoo'."
    echo "  -V    Show $SCRIPT version."
    echo "  help  Show $SCRIPT manual."
    echo
}

# Show help and exit
if [[ "$1" == "help" ]]; then
    Help
    exit
fi

# Process params
while getopts ":c: :V" opt; do
    case $opt in
        c) CONTAINER="$OPTARG";;
        V) echo "$SCRIPT version $VERSION"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        Help
        exit;;
    esac
done

curl -4 ifconfig.co
