#!/usr/bin/env bash
set -e

script=$(basename "$0")
version="1.0.1"

help() {
    echo
    echo "$script"
    echo
    echo 'Description: Show public facing ip of server.'
    echo "Syntax: $script [-V|help]"
    echo "Example: $script"
    echo 'options:'
    echo "  -c    Docker container. Defaults to 'odoo'."
    echo "  -V    Show $script version."
    echo "  help  Show $script manual."
    echo
}

if [[ "$1" == "help" ]]; then
    help
    exit
fi

while getopts ":c: :V" opt; do
    case $opt in
        c) container="$OPTARG";;
        V) echo "$script version $version"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        help
        exit;;
    esac
done

curl -4 ifconfig.co
