#!/bin/bash
set -e

REPOSITORY=https://raw.githubusercontent.com/mint-system/ansible-build

SCRIPTS=(
    docker-nginx-enable
    docker-nginx-reload
    parse-url
    get-public-ip
)

for SCRIPT in ${SCRIPTS[@]}; do
    echo "Install $SCRIPT script ..."
    sudo curl -L "$REPOSITORY/main/roles/nginx/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
    sudo chmod +x "/usr/local/bin/$SCRIPT"
done
