#!/bin/bash
set -e

REPOSITORY=https://ansible.build

SCRIPTS=(
    docker-nginx-enable
    docker-nginx-reload
    get-public-ip
)

for SCRIPT in ${SCRIPTS[@]}; do
    echo "Install $SCRIPT script ..."
    sudo curl -L "$REPOSITORY/nginx/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
    sudo chmod +x "/usr/local/bin/$SCRIPT"
done
