#!/bin/bash

# Jetty herunterladen
wget https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.2.17.v20160517/jetty-distribution-9.2.17.v20160517.zip

# BIRT Runtime herunterladen
wget https://download.eclipse.org/birt/downloads/drops/R-R1-4_5_0-201506092134/birt-runtime-4.5.0-20150609.zip
unzip birt-runtime-4.5.0-20150609.zip birt-runtime-4_5_0/birt.war
mv -f birt-runtime-4_5_0/birt.war birt-runtime-4.5.0.war
rm -f birt-runtime-4.5.0-20150609.zip
rmdir birt-runtime-4_5_0

# Postgres JDBC herunterladen
wget http://jdbc.postgresql.org/download/postgresql-9.4.1208.jre7.jar

# AS400 JDBC herunterladen
wget http://downloads.sourceforge.net/project/jt400/JTOpen-full/9.0/jtopen_9_0.zip
unzip jtopen_9_0.zip lib/jt400.jar
mv -f lib/jt400.jar .
rm -f jtopen_9_0.zip
rmdir lib
chmod 644 jt400.jar
