---
- name: Copy {{ role_name }} scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/bin/{{ item }}
    mode: +x
  loop:
    - docker-nginx-reload
    - docker-nginx-enable
    - get-public-ip

- name: Copy {{ nginx_hostname }} templated scripts
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /usr/local/bin/{{ item }}
    mode: +x
  loop:
    - nginx-maintance-redirect
