#!/bin/bash

# Exit script if command fails
# -u stops the script on unset variables
# -e stops the script on errors
# -o pipefail stops the script if a pipe fails
set -e

REPOSITORY=https://raw.githubusercontent.com/mint-system/ansible-playbooks

SCRIPT="docker-odoo-install"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo-scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="docker-odoo-user"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo-scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="odoo-user"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo-scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="odoo-backup"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo-scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="odoo-restore"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo-scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="docker-odoo-list"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo-scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"