#!/bin/bash
set -e

# Get script name
SCRIPT=$(basename "$0")
VERSION="1.0.0"

# Display Help
Help() {
    echo
    echo "$SCRIPT"
    echo
    echo "Description: Uninstall Odoo modules in Docker container."
    echo "Syntax: $SCRIPT [-c|-d|-u|-V|help]"
    echo "Example: $SCRIPT -c odoo01 -d erp -r hr_timesheet"
    echo "options:"
    echo "  -c    Docker container. Defaults to 'odoo'."
    echo "  -d    Database name."
    echo "  -u    Name of Odoo module to uninstall."
    echo "  -V    Show $SCRIPT version."
    echo "  help  Show $SCRIPT manual."
    echo
}

# Show help and exit
if [[ "$1" == "help" ]]; then
    Help
    exit
fi

# Process params
while getopts ":c: :d: :u: :V" opt; do
    case $opt in
        c) CONTAINER="$OPTARG";;
        d) DATABASE="$OPTARG";;
        u) MODULE="$OPTARG";;
        V) echo "$SCRIPT version $VERSION"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        Help
        exit;;
    esac
done

# Fallback to environment vars and default values
: ${CONTAINER:='odoo'}

# Verify variables
[[ -z "$DATABASE" ]] && { echo "Parameter -d|database is empty" ; exit 1; }

# Remove with Docker exec
echo "Remove module $MODULE on database $DATABASE on container $CONTAINER."
docker exec $CONTAINER bash -c "echo \"self.env['ir.module.module'].search([('name', '=', '$MODULE')]).button_immediate_uninstall()\" | odoo shell -d $DATABASE --db_host=\$HOST -r \$USER -w \$PASSWORD --no-http"
