#!/bin/bash
set -e

SCRIPT=$(basename "$0")
VERSION="1.0.0"

# Display Help
Help() {
    echo
    echo "$SCRIPT"
    echo
    echo "Description: Run Odoo upgrade scripts for target PostgreSQL database."
    echo "Syntax: $SCRIPT [-c|-s|-t|-r|-u|-V|help]"
    echo "Example: $SCRIPT -c postgres01 -h localhost -d erp -s 16.0 -n upgrade -t 17.0 -m test -l MXXXXXXXXX"
    echo "options:"
    echo "  -c    PostgreSQL container. Defaults to 'postgres'."
    echo "  -h    PostgreSQL hostname. Defaults to container name."
    echo "  -d    Current database name."
    echo "  -s    Current Odoo version."
    echo "  -n    Target database name."
    echo "  -t    Target Odoo version."
    echo "  -l    Optional Odoo subscription code."
    echo "  -m    Upgrade mode. Options are 'test' or 'production'. Defaults to 'test'."
    echo "  -V    Show $SCRIPT version."
    echo "  help  Show $SCRIPT manual."
    echo
}

# Show help and exit
if [[ "$1" == "help" ]]; then
    Help
    exit
fi

# Check requiremements
command -v rsync >/dev/null 2>&1 || { echo >&2 "rsync not found: apt-get install rsync"; exit 1; }
command -v ssh-keygen >/dev/null 2>&1 || { echo >&2 "ssh-keygen not found: apt-get install openssh-client"; exit 1; }
command -v psql >/dev/null 2>&1 || { echo >&2 "psql not found: apt-get install postgresql-client-1X"; exit 1; } # 
command -v python3 >/dev/null 2>&1 || { echo >&2 "python3 not found: apt-get install python3"; exit 1; } # 

# Process params
while getopts ":c: :h: :d: :s: :n: :t: :m: :l: :V" opt; do
    case $opt in
        c) CONTAINER="$OPTARG";;
        h) HOSTNAME="$OPTARG";;
        d) DATABASE="$OPTARG";;
        s) ODOO_CURRENT_VERSION="$OPTARG";;
        n) NEW_DATABASE="$OPTARG";;
        t) ODOO_TARGET_VERSION="$OPTARG";;
        m) MODE="$OPTARG";;
        l) LICENSE="$OPTARG";;
        V) echo "$SCRIPT version $VERSION"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        Help
        exit;;
    esac
done

# Fallback to environment vars and default values
: "${CONTAINER:=postgres}"
: "${HOSTNAME:=$CONTAINER}"
: "${CONTAINER:=5432}"
: "${MODE:=test}"

# Verify variables
[[ -z "$DATABASE" ]] && { echo "Parameter -d|database is empty" ; exit 1; }
[[ -z "$ODOO_CURRENT_VERSION" ]] && { echo "Parameter -s|current version is empty" ; exit 1; }
[[ -z "$NEW_DATABASE" ]] && { echo "Parameter -n|new database is empty" ; exit 1; }
[[ -z "$ODOO_TARGET_VERSION" ]] && { echo "Parameter -t|target version is empty" ; exit 1; }

# Retrieve database credentials
PGHOST="$HOSTNAME"
PGUSER=$(docker exec "$CONTAINER" /bin/bash -c "echo \$POSTGRES_USER")
PGPASSWORD=$(docker exec "$CONTAINER" /bin/bash -c "echo \$POSTGRES_PASSWORD")
export PGHOST
export PGUSER
export PGPASSWORD

echo "Run upgrade script for database $DATABASE in $MODE mode."
echo "The database will be upgraded from $ODOO_CURRENT_VERSION to $ODOO_TARGET_VERSION."
if [ -z "$LICENSE" ]; then
    python3 <(curl -s https://upgrade.odoo.com/upgrade) "$MODE" -d "$DATABASE" -t "$ODOO_TARGET_VERSION" -r "$NEW_DATABASE"
else
    python3 <(curl -s https://upgrade.odoo.com/upgrade) "$MODE" -d "$DATABASE" -t "$ODOO_TARGET_VERSION" -r "$NEW_DATABASE" -c "$LICENSE"
fi
echo "The upgrade has been successful. The upgraded database has been restored as '$NEW_DATABASE'."
