#!/bin/bash
set -e

# Get script name
SCRIPT=$(basename "$0")
VERSION="1.0.0"

# Display Help
Help() {
    echo
    echo "$SCRIPT"
    echo
    echo "Description: Neutralize Odoo database."
    echo "Syntax: $SCRIPT [-c|-d|-V|help]"
    echo "Example: $SCRIPT -c odoo08 -d shop"
    echo "options:"
    echo "  -c    Docker database container. Defaults to 'odoo'."
    echo "  -d    Database name. Defaults to 'odoo'."
    echo "  -V    Show $SCRIPT version."
    echo "  help  Show $SCRIPT manual."
    echo
}

# Show help and exit
if [[ "$1" == "help" ]]; then
  Help
  exit
fi

# Process params
while getopts ":c: :d: :V" opt; do
    case $opt in
        c) CONTAINER="$OPTARG" ;;
        d) DATABASE="$OPTARG" ;;
        V) echo "$SCRIPT version $VERSION"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        Help
        exit;;
    esac
done

# Fallback to environment vars and default values
: ${CONTAINER:='odoo'}

# Verify variables
[[ -z "$DATABASE" ]] && { echo "Parameter -d|database is empty" ; exit 1; }

docker exec -it $CONTAINER /bin/bash -c "odoo neutralize -d $DATABASE --db_host \$HOST -r \$USER -w \$PASSWORD"
