#!/bin/bash
set -e

# Get script name
SCRIPT=$(basename "$0")
VERSION="1.0.0"

# Display Help
Help() {
  echo
  echo "$SCRIPT"
  echo
  echo "Description: Clear all assets of Odoo instance."
  echo "Syntax: $SCRIPT [-c|-d|-V|help]"
  echo "Example: $SCRIPT -c odoo01 -d erp"
  echo "options:"
  echo "  -c    Docker container. Defaults to 'odoo'."
  echo "  -d    Database name. Defaults to 'odoo'."
  echo "  -v    Show $SCRIPT version."
  echo "  help  Show $SCRIPT manual."
  echo
}

# Show help and exit
if [[ "$1" == "help" ]]; then
  Help
  exit
fi

# Process params
while getopts ":c: :d: :V" opt; do
    case $opt in
        c) CONTAINER="$OPTARG" ;;
        d) DATABASE="$OPTARG" ;;
        V) echo "$SCRIPT version $VERSION"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        Help
        exit;;
    esac
done

# Verify variables
[[ -z "$CONTAINER" ]] && { echo "Parameter -c|container is empty" ; exit 1; }
[[ -z "$DATABASE" ]] && { echo "Parameter -d|database is empty" ; exit 1; }

echo "Delete these assets on $CONTAINER for $DATABASE:"
docker exec "$CONTAINER" /bin/bash -c "psql postgresql://\$USER:\$PASSWORD@\$HOST/$DATABASE -c \"SELECT id,name FROM ir_attachment WHERE res_model='ir.ui.view' and name like '%assets_%';\""
docker exec "$CONTAINER" /bin/bash -c "psql postgresql://\$USER:\$PASSWORD@\$HOST/$DATABASE -c \"DELETE FROM ir_attachment WHERE res_model='ir.ui.view' and name like '%assets_%';\""

echo "Restart the Odoo container".
docker restart "$CONTAINER"