#!/bin/bash
set -e

# Get script name
SCRIPT=$(basename "$0")

# Display Help
Help() {
    echo
    echo "$SCRIPT"
    echo
    echo "Description: Update Odoo modules in Docker container."
    echo "Syntax: $SCRIPT [-d|-m|-c|help]"
    echo "Example: $SCRIPT -d erp -u hr_timesheet -c odoo01"
    echo "options:"
    echo "  -d    Database name. Defaults to 'odoo'."
    echo "  -u    List of odoo modules to update. Defaults to 'all'."
    echo "  -c    Docker container. Defaults to 'odoo'."
    echo "  help  Show $SCRIPT manual."
    echo
}

# Show help and exit
if [[ $1 == 'help' ]]; then
    Help
    exit
fi

# Process params
while getopts ":d: :u: :c:" opt; do
  case $opt in
    u) MODULES="$OPTARG";;
    c) CONTAINER="$OPTARG";;
    d) DATABASE="$OPTARG";;
    \?) echo "Invalid option -$OPTARG" >&2
    Help
    exit;;
  esac
done

# Fallback to environment vars and default values
: ${DATABASE:='odoo'}
: ${CONTAINER:='odoo'}
: ${MODULES:='all'}

# Update with Docker exec
echo "Update modules $MODULES for database $DATABASE on container $CONTAINER."
docker exec -it $CONTAINER bin/bash -c "odoo -c /etc/odoo/odoo.conf -d $DATABASE -u $MODULES --db_host \$HOST -r \$USER -w \$PASSWORD --stop-after-init --no-http"

echo "The Odoo update for $CONTAINER has finished."
