#!/bin/bash
set -e

# Get script name
SCRIPT=$(basename "$0")
VERSION="1.0.0"

# Display Help
Help() {
    echo
    echo "$SCRIPT"
    echo
    echo "Description: Run python code in Odoo container."
    echo "Syntax: $SCRIPT [-c|-d|-p|-f|-V|help]"
    echo "Example: $SCRIPT -d erp-dev -c odoo06 -p 'print(env.user.name)'"
    echo "options:"
    echo "  -c    Docker container. Defaults to 'odoo'."
    echo "  -d    Database name."
    echo "  -p    Python code as string."
    echo "  -f    Commit changes to database."
    echo "  -V    Show $SCRIPT version."
    echo "  help  Show $SCRIPT manual."
    echo
}

# Show help and exit
if [[ "$1" == "help" ]]; then
    Help
    exit
fi

# Initialise option flag
FORCE='false'

# Process params
while getopts ":c: :d: :p: :f :V" opt; do
    case $opt in
        c) CONTAINER="$OPTARG";;
        d) DATABASE="$OPTARG";;
        p) CODE="$OPTARG";;
        f) FORCE='true';;
        V) echo "$SCRIPT version $VERSION"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        Help
        exit;;
    esac
done

# Fallback to environment vars and default values
: ${CONTAINER:='odoo'}

# Verify variables
[[ -z "$DATABASE" ]] && { echo "Parameter -d|database is empty" ; exit 1; }

# Switch container name with id
CONTAINER_ID=$(docker ps -f "name=${CONTAINER}" -q | tail -n1)
[[ -z "$CONTAINER_ID" ]] && { echo "Container id for $CONTAINER not found." ; exit 1; }

# Escape quotes
CODE=$(echo "$CODE" | sed 's/"/\\"/g' | sed "s/'/\\'/g")

# Append commit command if forced
if $FORCE; then
    CODE="${CODE};self.env.cr.commit()"
fi

if [[ -n $CODE ]]; then
    echo "Execute code in container $CONTAINER on database $DATABASE." >&2
    docker exec $CONTAINER_ID /bin/bash -c "echo \"$CODE\" | odoo shell -d $DATABASE --db_host=\$HOST --db_user=\$USER --db_password=\$PASSWORD --no-http"
else
    echo "Start odoo shell in container $CONTAINER on database $DATABASE."
    docker exec -it $CONTAINER_ID /bin/bash -c "odoo shell -d $DATABASE --db_host=\$HOST --db_user=\$USER --db_password=\$PASSWORD --no-http"
fi

if $FORCE; then
    echo "Changes to the database have been committed." >&2
fi
