#!/usr/bin/env bash
set -e

# Get script name
script=$(basename "$0")
version="1.0.0"

# Display Help
help() {
    echo
    echo "$script"
    echo
    echo 'Description: Uninstall Odoo modules in Docker container.'
    echo "Syntax: $script [-c|-d|-u|-V|help]"
    echo 'Example: $script -c odoo01 -d erp -u hr,note'
    echo 'options:'
    echo '  -c    Docker container. Defaults to '\''odoo'\''.'
    echo '  -d    Database name.'
    echo '  -u    Name of Odoo module to uninstall.'
    echo '  -V    Show $script version.'
    echo '  help  Show $script manual.'
    echo
}

# Show help and exit
if [[ "$1" == 'help' ]]; then
    help
    exit
fi

# Process params
while getopts ':c: :d: :u: :V' opt; do
    case $opt in
        c) container="$OPTARG";;
        d) database="$OPTARG";;
        u) modules="$OPTARG";;
        V) echo "$script version $version"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        help
        exit;;
    esac
done

# Fallback to environment vars and default values
: "${container:=odoo}"

# Verify variables
[[ -z "$database" ]] && { echo 'Parameter -d|database is empty' ; exit 1; }
[[ -z "$modules" ]] && { echo 'Parameter -u|module is empty' ; exit 1; }

# Split modules by comma and loop through them
IFS=',' read -ra MODULES <<< "$modules"
for module in "${MODULES[@]}"; do
    module=$(echo "$module" | xargs)
    [[ -z "$module" ]] && continue

    echo "Removing module '$module' on database '$database' on container '$container'."
    docker exec $container /bin/bash -c "echo \"self.env['ir.module.module'].search([('name', '=', '$module')]).button_immediate_uninstall()\" | odoo shell -d $database --db_host=\$HOST --db_user=\$USER --db_password=\$PASSWORD --no-http"
done
