#!/bin/bash
set -e

# Get script name
SCRIPT=$(basename "$0")
VERSION="1.0.0"

# Display Help
Help() {
    echo
    echo "$SCRIPT"
    echo
    echo "Description: List all Odoo databases in Docker container."
    echo "Syntax: $SCRIPT [-c|-v|help]"
    echo "Example: $SCRIPT -c odoo01"
    echo "options:"
    echo "  -c    Docker container. Defaults to 'odoo'."
    echo "  -v    Show $SCRIPT version."
    echo "  help  Show $SCRIPT manual."
    echo
}

# Show help and exit
if [[ $1 == 'help' ]]; then
    Help
    exit
fi

# Process params
while getopts ":c: :v" opt; do
    case $opt in
        c) CONTAINER="$OPTARG";;
        v) echo "$SCRIPT version $VERSION"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        Help
        exit;;
    esac
done

# Fallback to environment vars and default values
: ${CONTAINER:='odoo'}

docker exec $CONTAINER bin/bash -c "psql postgresql://\$USER:\$PASSWORD@\$HOST/postgres -tAc 'select datname from pg_database'"
