#!/bin/bash
set -e

# Get script name
SCRIPT=$(basename "$0")
VERSION="1.0.1"

# Display Help
Help() {
    echo
    echo "$SCRIPT"
    echo
    echo "Description: Backup Odoo database from container."
    echo "Syntax: $SCRIPT [-d|-c|-f|-r|-u|-V|help]"
    echo "Example: $SCRIPT -d erp-dev -c postgres01 -f tmp/erp.zip -r -p ~/.local/share/Odoo/filestore"
    echo "options:"
    echo "  -d    Database name. Defaults to filename."
    echo "  -c    Postgres container. Defaults to 'odoo'."
    echo "  -f    Odoo database backup file. Defaults to '/var/tmp/odoo.zip'."
    echo "  -r    Replace existing database."
    echo "  -p    Path to the filestore. Defaults to '~/.local/share/Odoo/filestore'"
    echo "  -V    Show $SCRIPT version."
    echo "  help  Show $SCRIPT manual."
    echo
}

# Show help and exit
if [[ "$1" == "help" ]]; then
    Help
    exit
fi

# Check requiremements
command -v uuidgen >/dev/null 2>&1 || { echo >&2 "uuidgen not found: apt-get install uuid-runtime"; exit 1; }

# Initialise option flag with a false value
REPLACE='false'

# Process params
while getopts ":c: :d: :f: :r :p :V" opt; do
    case $opt in
        c) CONTAINER="$OPTARG";;
        d) DATABASE="$OPTARG";;
        f) FILE="$OPTARG";;
        r) REPLACE='true';;
        p) FILESTORE_PATH='true';;
        V) echo "$SCRIPT version $VERSION"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        Help
        exit;;
    esac
done

# Fallback to environment vars and default values
: ${CONTAINER:='postgres'}
: ${FILE:='/var/tmp/odoo.zip'}
: ${FILESTORE_PATH:='~/.local/share/Odoo/filestore'}

# Get file and directory name
DIR=`dirname "$FILE"`
FILENAME=`basename "$FILE"`
: ${DATABASE:="${FILENAME::-4}"}

# Start restore
echo "Requesting restore for Odoo database from $FILENAME to $DATABASE ..."

# Set alias
docker_exec_bash="docker exec -e DATABASE=$DATABASE $CONTAINER /bin/bash -c"
docker_exec_root_bash="docker exec --user root -e DATABASE=$DATABASE $CONTAINER /bin/bash -c"

# Unip archive
echo "Unzip archive."
cd $DIR
unzip -q -o $FILENAME

# Clear database
if $REPLACE; then
    echo "Remove filestore $FILESTORE_PATH/$DATABASE."
    rm -rf "$FILESTORE_PATH/$DATABASE"
    docker-postgres-drop -c "$CONTAINER" -d "$DATABASE"
fi

# Copy filestore
echo "Move filestore."
mv filestore "$FILESTORE_PATH/$DATABASE"

# Create database
echo "Create database $DATABASE."
docker exec "$CONTAINER" /bin/bash -c "createdb -U \$POSTGRES_USER -T template0 $DATABASE"

# Restore database
echo "Restore database from $DATABASE."
docker-postgres-restore -c "$CONTAINER" -d "$DATABASE" -f 

# Remove source files
echo "Cleanup source files."
rm -rf dump.sql filestore

# Notify if backup has finished
echo "The restore for Odoo database $DATABASE has finished."
