#!/bin/bash
set -e

REPOSITORY=https://raw.githubusercontent.com/mint-system/ansible-build

SCRIPT="docker-odoo-install"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="docker-odoo-backup"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="docker-odoo-drop"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="docker-odoo-restore"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="docker-odoo-user"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="odoo-user"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="odoo-backup"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="odoo-restore"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="docker-odoo-list"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="parse-url"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="odoo-drop"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="odoo-duplicate"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="docker-odoo-clear-assets"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="docker-odoo-update"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="docker-odoo-uninstall"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="docker-odoo-patch"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"

SCRIPT="docker-odoo-cloc"
echo "Install $SCRIPT script ..."
sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
sudo chmod +x "/usr/local/bin/$SCRIPT"
