#!/bin/bash
set -e

REPOSITORY=https://raw.githubusercontent.com/mint-system/ansible-build

SCRIPTS=(
    docker-odoo-backup
    docker-odoo-clear-assets
    docker-odoo-cloc
    docker-odoo-drop
    docker-odoo-duplicate
    docker-odoo-init
    docker-odoo-list
    docker-odoo-patch
    docker-odoo-restore
    docker-odoo-shell
    docker-odoo-uninstall
    docker-odoo-update
    docker-odoo-user
    docker-odoo-neutralize
    odoo-backup
    odoo-drop
    odoo-duplicate
    odoo-restore
    odoo-user
)

for SCRIPT in ${SCRIPTS[@]}; do
    echo "Install $SCRIPT script ..."
    sudo curl -L "$REPOSITORY/master/roles/odoo_scripts/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
    sudo chmod +x "/usr/local/bin/$SCRIPT"
done
