#!/usr/bin/env bash
set -e

# Get script name
script=$(basename "$0")
version="1.0.0"

# Display Help
help() {
    echo
    echo "$script"
    echo
    echo 'Description: Export Docker volume content.'
    echo "Syntax: $script [-v|-p|-o|-V|help]"
    echo 'Example: $script -v odoo01 -p /filestore/odoo -o /tmp'
    echo 'options:'
    echo '  -v    Name of Docker volume.'
    echo "  -p    Path in volume. Defaults to '/'"
    echo "  -o    Output directory. Defaults to '/var/tmp'"
    echo "  -V    Show $script version."
    echo "  help  Show $script manual."
    echo
}

# Show help and exit
if [[ "$1" == 'help' ]]; then
    help
    exit
fi

# Initialise option flag with a false value
all='false'

# Process params
while getopts ":v: :p: :o: :V" opt; do
    case $opt in
        v) volume="$OPTARG"
        ;;
        p) path="$OPTARG"
        ;;
        o) dir="$OPTARG"
        ;;
        V) echo "$script version $version"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        help
        exit 1;;
    esac
done

# Fallback to environment vars and default values
: "${path:=/}"
: "${dir:=/var/tmp}"

# Verify variables
[[ -z "$volume" ]] && [[ -z "$all" ]] && { echo 'Parameter -v|volume' ; exit 1; }

# Run export 
echo "Export content of $volume volume with $path path..."
docker run --rm -v "$volume:/source" -v "${dir}:/backup" alpine tar -cf "/backup/$volume.tar" -C "/source$path" .

# Notify if export has finished
echo "Docker volume export has finished: ${dir}/{$volume}.tar"
