#!/bin/bash
set -e

# Get script name
SCRIPT=$(basename "$0")
VERSION="1.0.0"

# Display Help
Help() {
    echo
    echo "$SCRIPT"
    echo
    echo "Description: Copy docker volumes."
    echo "Syntax: $SCRIPT [-s|-t|-r|-v|help]"
    echo "Example: $SCRIPT -s jenkins -t jenkins_data01"
    echo "options:"
    echo "  -s    Source Docker volume name."
    echo "  -t    Target Docker volume name."
    echo "  -r    Replace existing target volume."
    echo "  -v    Show $SCRIPT version."
    echo "  help  Show $SCRIPT manual."
    echo
}

# Show help and exit
if [[ "$1" == "help" ]]; then
    Help
    exit
fi

# Initialise option flags
REPLACE="false"

# Process params
while getopts ":s: :t: :r :v" opt; do
    case $opt in
        s) SOURCE="$OPTARG"
        ;;
        t) TARGET="$OPTARG"
        ;;
        r) REPLACE="true"
        ;;
        v) echo "$SCRIPT version $VERSION"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        Help
        exit;;
    esac
done

# Verify variables
[[ -z "$SOURCE" ]] && { echo "Parameter -s|source is empty" ; exit 1; }
[[ -z "$TARGET" ]] && { echo "Parameter -t|target is empty" ; exit 1; }

if $REPLACE; then
    echo "Remove docker volume $TARGET."
    docker volume rm "$TARGET"
fi

docker volume inspect "$TARGET" > /dev/null && { echo "Docker volume $TARGET already exists." ; exit 1; }

echo "Create docker volume $TARGET."
docker volume create --name "$TARGET"

echo "Copy Docker volume content from $SOURCE to $TARGET."
docker container run --rm -it \
    -v "$SOURCE":/from \
    -v "$TARGET":/to \
    alpine ash -c "cd /from ; cp -av . /to" \
    > /dev/null && { echo "Docker volume copy has finished."; }
