#!/usr/bin/env bash
set -e

repository='https://ansible.build'

scripts=(
    docker-disk-usage
    docker-volume-backup
    docker-volume-export
    docker-volume-import
    docker-volume-list
    docker-volume-restore
    docker-volume-copy
)

install_dir='/usr/local/bin'

if [[ "$1" == '--user' ]]; then
    install_dir="$HOME/.local/bin"
    mkdir -p "$install_dir"
    echo "Installing scripts in $install_dir"
fi

for script in "${scripts[@]}"; do
    echo "Installing $script ..."
    curl -L "$repository/docker_volume/$script" -o "$install_dir/$script"
    chmod +x "$install_dir/$script"
done
