#!/bin/bash
set -e

REPOSITORY=https://ansible.build

SCRIPTS=(
    docker-disk-usage
    docker-volume-backup
    docker-volume-restore
    docker-volume-copy
)

INSTALL_DIR="/usr/local/bin"

if [[ "$1" == "--user" ]]; then
    INSTALL_DIR="$HOME/bin"
    mkdir -p "$INSTALL_DIR"
    echo "Installing scripts in $INSTALL_DIR"
fi

for SCRIPT in ${SCRIPTS[@]}; do
    echo "Installing $SCRIPT ..."
    curl -L "$REPOSITORY/docker_volume/$SCRIPT" -o "$INSTALL_DIR/$SCRIPT"
    chmod +x "$INSTALL_DIR/$SCRIPT"
done