---
- name: Register bbb_install packages
  ansible.builtin.shell: dpkg -l | grep bbb | cut -d' ' -f3
  changed_when: false
  register: bbb_packages

- name: Uninstall bbb_install
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ bbb_packages.stdout_lines }}"

- name: Uninstall bbb_install dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  loop:
    - nginx

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
