#!/usr/bin/env bash
set -e

repository=https://ansible.build

scripts=(
    ansible-vault-get
)

for script in "${scripts[@]}"; do
    echo "Install $script script ..."
    sudo curl -L "$repository/ansible_scripts/$script" -o "/usr/local/bin/$script"
    sudo chmod +x "/usr/local/bin/$script"
done
