#!/bin/bash
set -e

REPOSITORY=https://ansible.build

SCRIPTS=(
    ansible-vault-get
)

for SCRIPT in ${SCRIPTS[@]}; do
    echo "Install $SCRIPT script ..."
    sudo curl -L "$REPOSITORY/ansible_scripts/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
    sudo chmod +x "/usr/local/bin/$SCRIPT"
done
