#!/bin/bash

# Exit script if command fails
# -u stops the script on unset variables
# -e stops the script on errors
# -o pipefail stops the script if a pipe fails
set -e

# Get script name
SCRIPT=$(basename "$0")

# Default configuration
PACKAGE_PATH="/usr/lib/python3/dist-packages/"

# Custom configuration
FILE_PATH="${PACKAGE_PATH}odoo/addons/hr_holidays/models/hr_leave.py"
FIND="note = _('New %s Request created by %s from %s to %s') % (holiday.holiday_status_id.name, holiday.create_uid.name, start, end)"
IFS='' read -r -d '' APPEND << EOM
            if holiday.name:
                note += _('<br/>Comment: %s') % (holiday.name)
EOM

# Get filename
FILE=`basename "$FILE_PATH"`

# Cop from docker
docker cp "$1":"$FILE_PATH" .

LINE=$(grep -n "$FIND" $FILE | cut -f1 -d:)

# Find and append
awk -v n="$LINE" -v s="$APPEND" 'NR-1 == n {print s} {print}' $FILE > $FILE.tmp && mv $FILE.tmp $FILE

# Copy back to docker
docker cp $FILE "$1":"$FILE_PATH"

# Register patch installation
echo "Patch $SCRIPT applied."
touch "/var/tmp/$SCRIPT"
