#!/bin/bash

# Get script name
SCRIPT=$(basename "$0")

# Default configuration
PACKAGE_PATH="/usr/lib/python3/dist-packages/"

# Custom configuration
FILE_PATH="${PACKAGE_PATH}odoo/addons/delivery/__manifest__.py"
FIND="'sale_stock', 'sale_management'"
REPLACE="'sale_stock'"

# Get filename
FILE=`basename "$FILE_PATH"`

# Cop from docker
docker cp "$1":"$FILE_PATH" .

# Find and replace
sed -i'' "s/$FIND/$REPLACE/g" $FILE

# Copy back to docker
docker cp $FILE "$1":"$FILE_PATH"

# Remove file
rm -f $FILE

# Register patch installation
echo "Patch $SCRIPT applied."
touch "/var/tmp/$SCRIPT"
