#!/bin/bash

docker cp "$1":/usr/lib/python3/dist-packages/odoo/addons/delivery/__manifest__.py .

sed -i'' "s/'sale_stock', 'sale_management'/'sale_stock'/g" __manifest__.py

docker cp __manifest__.py "$1":/usr/lib/python3/dist-packages/odoo/addons/delivery/__manifest__.py

touch /var/tmp/odoo14_delivery_patch_installed
