#!/bin/bash

# Get script name
SCRIPT=$(basename "$0")

# Default configuration
PACKAGE_PATH="/usr/lib/python3/dist-packages/"

# Custom configuration
FILE_PATH="${PACKAGE_PATH}odoo/addons/hr_holidays/models/hr_leave.py"
FIND="report_note = fields.Text('HR Comments', copy=False, groups=\"hr_holidays.group_hr_holidays_manager\")"
REPLACE="report_note = fields.Text('HR Comments', copy=False, groups=\"hr_holidays.group_hr_holidays_responsible\")"

# Get filename
FILE=`basename "$FILE_PATH"`

# Cop from docker
docker cp "$1":"$FILE_PATH" .

# Find and replace
sed -i'' "s/$FIND/$REPLACE/g" $FILE

# Copy back to docker
docker cp $FILE "$1":"$FILE_PATH"

# Register patch installation
echo "Patch $SCRIPT applied."
touch "/var/tmp/$SCRIPT"
