#!/bin/bash
set -e

# Get script name
SCRIPT=$(basename "$0")
VERSION="1.0.0"

# Display Help
Help() {
  echo
  echo "$SCRIPT"
  echo
  echo "Description: List jobs from crontab managed by Ansible."
  echo "Syntax: $SCRIPT [-u|-V|help]"
  echo "Example: $SCRIPT -u root"
  echo "options:"
  echo "  -u    Specify username of crontab."
  echo "  -V    Show $SCRIPT version."
  echo "  help  Show $SCRIPT manual."
  echo
}

# Show help and exit
if [[ "$1" == "help" ]]; then
    Help
    exit
fi

# Initialize variables
: ${CRONTAB_USERNAME:="$USERNAME"}
: ${CRONTAB_USERNAME:=$(whoami)}

# Process params
while getopts ":u: :V" opt; do
  case $opt in
    u) CRONTAB_USERNAME="$OPTARG";;
    V) echo "$SCRIPT version $VERSION"
    exit 0
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    Help
    exit 1;;
  esac
done

sudo crontab -u "$CRONTAB_USERNAME" -l | awk '
  BEGIN { job_num = 1 }
  /^#Ansible: / {
    # Capture the full job name (everything after "#Ansible: ")
    sub(/^#Ansible: /, "", $0);
    job_name = $0;
    getline;
    print "[" job_num "]", $1, $2, $3, $4, $5, job_name;
    job_num++;
  }
'