#!/usr/bin/env bash
set -e

repository='https://ansible.build'

scripts=(
    cron-job-run
    cron-job-list
)

for script in "${scripts[@]}"; do
    echo "Install $script script ..."
    sudo curl -L "$repository/cron/$script" -o "/usr/local/bin/$script"
    sudo chmod +x "/usr/local/bin/$script"
done
