#!/usr/bin/env bash
set -e

# Get script name
script=$(basename "$0")
version="1.0.1"

# Display Help
help() {
    echo
    echo "$script"
    echo
    echo 'Description: Restore Odoo database from zip file.'
    echo "Syntax: $script [-d|-c|-f|-r|-u|-V|help]"
    echo 'Example: $script -d erp-dev -c odoo06 -f tmp/erp.zip -r'
    echo 'options:'
    echo '  -d    Database name. Defaults to filename.'
    echo '  -c    Odoo container. Defaults to '\''odoo'\''.'
    echo '  -f    Odoo database backup file. Defaults to '\''/var/tmp/odoo.zip'\''.'
    echo '  -r    Replace existing database.'
    echo '  -u    Update database uuid.'
    echo '  -V    Show $script version.'
    echo "  help  Show $script manual."
    echo
}

# Show help and exit
if [[ "$1" == 'help' ]]; then
    help
    exit
fi

# Initialise option flag with a false value
replace='false'
update='false'

# Process params
while getopts ':c: :d: :f: :r :u :V' opt; do
    case $opt in
        c) container="$OPTARG";;
        d) database="$OPTARG";;
        f) file="$OPTARG";;
        r) replace='true';;
        u) update='true';;
        V) echo "$script version $version"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        help
        exit;;
    esac
done

# Fallback to environment vars and default values
: "${container:=odoo}"
: "${file:=/var/tmp/odoo.zip}"

# Get file and directory name
dir=$(dirname "$file")
filename=$(basename "$file")
: ${database:="${filename::-4}"}

echo "Requesting restore for Odoo database from $filename to $database ..."

echo 'Unzip archive.'
cd $dir
unzip -q -o $filename

# Clear database
if $replace; then
    docker-odoo-drop -c "$container" -d "$database"
fi

echo 'Copy filestore.'
docker cp filestore/ "$container:/var/lib/odoo/filestore/$database"

echo "Create database $database."
docker exec $container /bin/bash -c "PGPASSWORD=\"\$PASSWORD\" createdb -h \$HOST -U \$USER -T template0 $database"

echo "Restore database from $database."
cat ./dump.sql | docker exec -i $container /bin/bash -c "psql postgres://\$USER:\$PASSWORD@\$HOST:5432/$database"

echo 'Cleanup source files.'
rm -rf dump.sql filestore

# Update database uuid
if $update; then
    command -v uuidgen >/dev/null 2>&1 || { echo >&2 'uuidgen not found: apt-get install uuid-runtime'; exit 1; }
    uuid=$(uuidgen)
    echo 'Update database uuid.'
    query="UPDATE ir_config_parameter SET value = '$uuid' WHERE key = 'database.uuid';"
    docker exec $container /bin/bash -c "psql postgres://\$USER:\$PASSWORD@\$HOST:5432/$database -c \"$query\""
fi

echo "The restore for Odoo database $database has finished."
