#!/usr/bin/env bash
set -e

script=$(basename "$0")
version="1.1.0"

help() {
    echo
    echo "$script"
    echo
    echo 'Description: Backup Odoo database from container.'
    echo "Syntax: $script [-d|-c|-o|-V|help]"
    echo 'Example: $script -d erp -c odoo06 -o tmp/erp.zip'
    echo 'options:'
    echo "  -d    Database name. Defaults to 'odoo'."
    echo "  -c    Docker container. Defaults to 'odoo'."
    echo "  -o    Output directory with or without filename. Defaults to '/var/tmp'."
    echo "        Use .zip extension for a zip archive, .tar for a rsyncable tar archive."
    echo "  -V    Show $script version."
    echo "  help  Show $script manual."
    echo
}

if [[ "$1" == 'help' ]]; then
    help
    exit
fi

command -v zip >/dev/null 2>&1 || { echo >&2 'zip command not found'; exit 1; }

database='odoo'
container='odoo'
output='/var/tmp'

while getopts ":d: :c: :o: :V" opt; do
    case $opt in
        c) container="$OPTARG";;
        d) database="$OPTARG";;
        o) output="$OPTARG";;
        V) echo "$script version $version"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        help
        exit;;
    esac
done

# Determine archive format from output extension
ext="${output##*.}"
if [[ "${output: -4}" == '.zip' ]]; then
    backup_dir=$(dirname "$output")
    backup_file=$(basename "$output")
    format='zip'
elif [[ "${output: -4}" == '.tar' ]]; then
    backup_dir=$(dirname "$output")
    backup_file=$(basename "$output")
    format='tar'
else
    backup_dir=$output
    format='zip'
fi

mkdir -p "$backup_dir"
if [[ -z "$backup_file" ]]; then
    backup_file="$database.${format}"
fi
filepath="${backup_dir}/${backup_file}"

container_id=$(docker ps -f "name=${container}" -q | head -n1)
[[ -z "$container_id" ]] && { echo "Container id for $container not found." ; exit 1; }

echo "Backup database $database to $filepath"

echo "Copy filestore from container $container_id"
rm -rf "$backup_dir/filestore"
docker cp "$container_id:/var/lib/odoo/filestore/$database" "$backup_dir/filestore"

docker_exec_bash="docker exec $container_id /bin/bash -c"

echo 'Dump database'
rm -f "$backup_dir/dump.sql"
$docker_exec_bash "pg_dump -h \"\$PGHOST\" -U \"\$PGUSER\" $database" > "$backup_dir/dump.sql"

echo "Archive filestore and dump to $backup_file"
rm -f "$filepath"
cd "$backup_dir"

if [[ "$format" == 'tar' ]]; then
    tar -cf "$backup_file" ./dump.sql ./filestore
else
    zip -q -r "$backup_file" ./dump.sql ./filestore
fi

echo 'Cleanup source files'
rm -rf dump.sql filestore

echo "The Odoo backup $filepath has finished."