#!/usr/bin/env bash
set -e

script=$(basename "$0")
version="1.0.1"

help() {
    echo
    echo "$script"
    echo
    echo 'Description: Count lines of code for Odoo database.'
    echo "Syntax: $script [-c|-d|-V|help]"
    echo 'Example: $script -c odoo08 -d shop'
    echo 'options:'
    echo '  -c    Docker database container. Defaults to '\''odoo'\''.'
    echo '  -d    Database name. Defaults to '\''odoo'\''.'
    echo '  -V    Show $script version.'
    echo "  help  Show $script manual."
    echo
}

if [[ "$1" == 'help' ]]; then
  help
  exit
fi

container=odoo

while getopts ':c: :d: :V' opt; do
    case $opt in
        c) container="$OPTARG" ;;
        d) database="$OPTARG" ;;
        V) echo "$script version $version"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        help
        exit;;
    esac
done

[[ -z "$database" ]] && { echo 'Parameter -d|database is empty' ; exit 1; }

docker exec -i $container /bin/bash -c "odoo cloc -c /etc/odoo/odoo.conf -d $database --db_host=\$HOST --db_user=\$USER --db_password=\$PASSWORD --stop-after-init --no-http"
