#!/usr/bin/env bash
set -e

script=$(basename "$0")
version="1.0.1"

help() {
    echo
    echo "$script"
    echo
    echo 'Description: Backup Odoo database from container.'
    echo "Syntax: $script [-d|-c|-o|-V|help]"
    echo 'Example: $script -d erp -c odoo06 -o tmp/erp.zip'
    echo 'options:'
    echo "  -d    Database name. Defaults to 'odoo'."
    echo "  -c    Docker container. Defaults to 'odoo'."
    echo "  -o    Output directory with or without filename. Defaults to '/var/tmp'."
    echo "  -V    Show $script version."
    echo "  help  Show $script manual."
    echo
}

if [[ "$1" == 'help' ]]; then
    help
    exit
fi

command -v zip >/dev/null 2>&1 || { echo >&2 'zip command not found'; exit 1; }

database='odoo'
container='odoo'
output='/var/tmp'

while getopts ":d: :c: :o: :V" opt; do
    case $opt in
        c) container="$OPTARG";;
        d) database="$OPTARG";;
        o) output="$OPTARG";;
        V) echo "$script version $version"
        exit 0
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        help
        exit;;
    esac
done

if [[ "${output: -4}" == '.zip' ]];then
    dir=$(dirname "$output")
    file=$(basename "$output")
else
    dir=$output
fi

mkdir -p $dir

if [[ -z "$file" ]];then
  file="$database.zip"
fi

filepath="${dir}/${file}"

container_id=$(docker ps -f "name=${container}" -q | head -n1)
[[ -z "$container_id" ]] && { echo "Container id for $container not found." ; exit 1; }

echo "Backup database $database to $filepath ..."

echo 'Copy filestore from container $container_id.'
rm -rf "$dir/filestore"
docker cp "$container_id:/var/lib/odoo/filestore/$database" "$dir/filestore"

docker_exec_bash="docker exec $container_id /bin/bash -c"

echo 'Dump database.'
$docker_exec_bash "PGPASSWORD=\"\$PASSWORD\" pg_dump -h \"\$HOST\" -U \"\$USER\" $database" > "$dir/dump.sql"

echo "Zip filestore and dump to $file."
rm -f "$filepath"
cd "$dir"
zip -q -r "$file" ./dump.sql ./filestore

echo 'Cleanup source files.'
rm -rf dump.sql filestore

echo "The Odoo backup has finished: $filepath"
