#!/usr/bin/env bash
set -e

repository='https://ansible.build'

scripts=(
    docker-odoo-backup
    docker-odoo-clear-assets
    docker-odoo-clear-views
    docker-odoo-cloc
    docker-odoo-drop
    docker-odoo-duplicate
    docker-odoo-init
    docker-odoo-list
    docker-odoo-patch
    docker-odoo-restore
    docker-odoo-shell
    docker-odoo-uninstall
    docker-odoo-update
    docker-odoo-user
    docker-odoo-neutralize
    docker-odoo-rename
    docker-odoo-upgrade
    odoo-backup
    odoo-drop
    odoo-duplicate
    odoo-restore
)

install_dir='/usr/local/bin'
completion_dir='/etc/bash_completion.d'

if [[ "$1" == '--user' ]]; then
    install_dir="$HOME/.local/bin"
    completion_dir="$HOME/.bash_completion.d"
    mkdir -p "$install_dir" "$completion_dir"
fi

for script in "${scripts[@]}"; do
    echo "Installing $script in $install_dir ..."
    curl -L "$repository/odoo/$script" -o "$install_dir/$script"
    chmod +x "$install_dir/$script"
done

echo "Installing docker-odoo completion scripts in $completion_dir ..."
curl -L "$repository/odoo/docker-odoo" -o "$completion_dir/docker-odoo"
chmod +x "$completion_dir/docker-odoo"
