#!/usr/bin/env bash
set -e

script=$(basename "$0")
version="1.0.1"

help() {
    echo
    echo "$script v$version"
    echo
    echo 'Description: Backup Odoo database in Kubernetes cluster.'
    echo "Syntax: $script <deployment> <database>"
    echo 'Example: $script odoo-odoo erp'
    echo 'Options:'
    echo "  help  Show $script manual."
    echo
}

if [[ "$1" == 'help' ]]; then
    help
    exit 0
fi

deployment="$1"
database="$2"

[[ -z "$deployment" ]] && { echo 'Error: Parameter deployment is empty'; exit 1; }
[[ -z "$database" ]] && { echo 'Error: Parameter database is empty'; exit 1; }

pod_id=$(kubectl get pods -l app="$deployment" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
if [[ -z "$pod_id" ]]; then
    echo "Error: No pod found for deployment '$deployment'"
    exit 1
fi

kubectl_exec="kubectl exec $pod_id -- /bin/bash -c"

echo "Backup database $database to /var/lib/odoo/$database.zip..."

echo 'Dump database.'
$kubectl_exec "PGPASSWORD=\"\$PASSWORD\" pg_dump -h \"\$HOST\" -U \"\$USER\" $database" > "/var/lib/odoo/dump.sql"

echo "Zip filestore and dump to $file."
zip -q -r "/var/lib/odoo/$database.zip" "/var/lib/odoo/dump.sql" "/var/lib/odoo/filestore/$database"

echo 'Cleanup dump.'
rm -rf "/var/lib/odoo/dump.sql"

echo "The Odoo backup has finished: /var/lib/odoo/$database.zip"