#!/bin/bash
set -e

# Get script name
SCRIPT=$(basename "$0")

# Display Help
Help() {
    echo
    echo "$SCRIPT"
    echo
    echo "Description: List all databases in Postgres Docker container."
    echo "Syntax: $SCRIPT [-c|help]"
    echo "Example: $SCRIPT -c postgres01"
    echo "options:"
    echo "  -c    Docker container. Defaults to 'postgres'."
    echo "  help  Show $SCRIPT manual."
    echo
}

# Show help and exit
if [[ "$1" == "help" ]]; then
    Help
    exit
fi

# Process params
while getopts ":c:" opt; do
  case $opt in
    c) CONTAINER="$OPTARG";;
    \?) echo "Invalid option -$OPTARG" >&2
    Help
    exit 1;;
  esac
done

# Verify variables
[[ -z "$CONTAINER" ]] && { echo "Parameter -c|container is empty" ; exit 1; }

docker exec "$CONTAINER" /bin/bash -c "psql postgresql://\$POSTGRES_USER:\$POSTGRES_PASSWORD@\$HOSTNAME:5432/postgres -tAc 'SELECT datname FROM pg_database;'"
