#!/bin/bash
set -e

SCRIPT=$(basename "$0")

Help() {
    echo
    echo "$SCRIPT"
    echo
    echo "Description: List all databases in Postgres Docker container."
    echo "Syntax: $SCRIPT [-c|help]"
    echo "Example: $SCRIPT -c postgres01"
    echo "options:"
    echo "  -c    Docker container. Defaults to 'postgres'."
    echo "  help  Show $SCRIPT manual."
    echo
}

if [[ "$1" == "help" ]]; then
    Help
    exit 0
fi

CONTAINER="postgres"  # default
while getopts ":c:" opt; do
  case $opt in
    c) CONTAINER="$OPTARG";;
    \?) echo "Invalid option -$OPTARG" >&2; Help; exit 1;;
  esac
done

# Validate container is set
[[ -z "$CONTAINER" ]] && { echo "Container name is required"; exit 1; }

docker exec \
  --env PGPASSWORD="$(docker exec "$CONTAINER" printenv POSTGRES_PASSWORD)" \
  "$CONTAINER" \
  psql -U "$(docker exec "$CONTAINER" printenv POSTGRES_USER)" \
  -h localhost -p 5432 -tAc "SELECT datname FROM pg_database WHERE datistemplate = false AND datname NOT IN ('template0', 'template1');"
