#!/usr/bin/env bash
set -e

repository=https://ansible.build

scripts=(
    write-node-exporter-metric
)

for script in "${scripts[@]}"; do
    echo "Install $script script ..."
    sudo curl -L "$repository/node_exporter/$script" -o "/usr/local/bin/$script"
    sudo chmod +x "/usr/local/bin/$script"
done
