#!/bin/bash
set -e

REPOSITORY=https://ansible.build

SCRIPTS=(
    write-node-exporter-metric
)

for SCRIPT in ${SCRIPTS[@]}; do
    echo "Install $SCRIPT script ..."
    sudo curl -L "$REPOSITORY/node_exporter/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
    sudo chmod +x "/usr/local/bin/$SCRIPT"
done
