#!/bin/bash

# Exit script if command fails
set -e

# Display Help
Help() {
  echo
  echo "odoo-restore"
  echo "############"
  echo
  echo "Description: Restore odoo database."
  echo "Syntax: odoo-restore [-p|-d|-f|-h|help]"
  echo "Example: odoo-restore -p secret -d odoo -f /tmp/odoo.zip -h https://odoo.example.org"
  echo "options:"
  echo "  -p    Odoo master password. Defaults to \$ODOO_MASTER_PASSWORD env var."
  echo "  -d    Database name."
  echo "  -f    Odoo database backup file. Defaults to '/var/tmp/odoo.zip'"
  echo "  -h    Odoo host. Defaults to 'http://localhost:8069'"
  echo "  help  Show odoo-restore manual."
  echo
}

# Show help and exit
if [[ $1 == 'help' ]]; then
    Help
    exit
fi

# Process params
while getopts ":p:d:f:h:help:" opt; do
  case $opt in
    h) HOST="$OPTARG"
    ;;
    p) PASSWORD="$OPTARG"
    ;;
    d) DATABASE="$OPTARG"
    ;;
    f) FILE="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    Help
    exit;;
  esac
done

# Fallback to environment vars and default values
: ${PASSWORD:=${ODOO_MASTER_PASSWORD}}
: ${FILE:='/var/tmp/odoo.zip'}
: ${HOST:='http://localhost:8069'}

# Verify variables
[[ -z "$PASSWORD" ]] && { echo "Parameter -p|password is empty" ; exit 1; }
[[ -z "$DATABASE" ]] && { echo "Parameter -d|database is empty" ; exit 1; }
[[ -z "$FILE" ]] && { echo "Parameter -f|file is empty" ; exit 1; }
[[ -z "$HOST" ]] && { echo "Parameter -h|host is empty" ; exit 1; }

# Validate zip file
unzip -t $FILE

# Start restore
echo "Requesting restore for Odoo database $DATABASE ..."

# Request restore with curl
curl \
  --silent \
  -F "master_pwd=${PASSWORD}" \
  -F "name=${DATABASE}" \
  -F backup_file=@$FILE \
  -F 'copy=true' \
  ${HOST}/web/database/restore | grep 'Redirecting...'

# Notify if restore has finished
echo "The restore for Odoo database $DATABASE has finished."
