#!/bin/bash
set -e

REPOSITORY=https://raw.githubusercontent.com/mint-system/ansible-build

SCRIPTS=(
    run-cron-job
    list-cron-job
)

for SCRIPT in ${SCRIPTS[@]}; do
    echo "Install $SCRIPT script ..."
    sudo curl -L "$REPOSITORY/master/roles/restic_client/files/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
    sudo chmod +x "/usr/local/bin/$SCRIPT"
done
