---
- name: Create {{ role_name }} volume
  community.docker.docker_volume:
    name: "{{ fathom_volume_name }}"

- name: Start {{ role_name }} container {{ fathom_hostname }}
  community.docker.docker_container:
    name: "{{ fathom_hostname }}"
    labels:
      description: "{{ fathom_description }}"
    image: "{{ fathom_image }}"
    restart_policy: unless-stopped
    volumes:
      - "{{ fathom_volume_name }}:/app"
    networks:
      - name: "{{ docker_network_name }}"
