---
- name: Odoo play
  hosts: all
  roles:
    - role: postgres
      tags: 
        - odoo
    - role: odoo
      tags: 
        - odoo
        - odoo_scripts
    - role: odoo_repos
      tags: odoo_repos