#!/bin/bash
set -e

REPOSITORY=https://ansible.build

SCRIPTS=(
    docker-certbot-create
    docker-certbot-delete
)

for SCRIPT in ${SCRIPTS[@]}; do
    echo "Install $SCRIPT script ..."
    sudo curl -L "$REPOSITORY/certbot/$SCRIPT" -o "/usr/local/bin/$SCRIPT"
    sudo chmod +x "/usr/local/bin/$SCRIPT"
done
