#!/usr/bin/env bash
set -e

repository='https://ansible.build'

scripts=(
    docker-certbot-create
    docker-certbot-delete
)

for script in "${scripts[@]}"; do
    echo "Install $script script ..."
    sudo curl -L "$repository/certbot/$script" -o "/usr/local/bin/$script"
    sudo chmod +x "/usr/local/bin/$script"
done
