#!/bin/bash

if [ -n "$1" ] && [ -f "$1" ]; then
  convert "$1" -resize 200x200\! "$1"
  echo "Resized: $1"
else
  for file in *.png; do
    [ -e "$file" ] && convert "$file" -resize 200x200\! "$file" && echo "Resized: $file"
  done
fi
