#!/usr/bin/env bash

if [[ -n "$1" ]] && [[ -f "$1" ]]; then
  magick "$1" -resize 200x200\! "$1"
  echo "Resized: $1"
else
  for file in *.png; do
    [[ -e "$file" ]] && magick "$file" -resize 200x200\! "$file" && echo "Resized: $file"
  done
fi
