---
- name: Execute this command as root
  ansible.builtin.fail:
    msg: wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v3.0.x-release/bbb-install.sh | bash -s -- -w -v jammy-300 -g -s {{
      bbb_install_hostname }} -e {{ bbb_install_certbot_email }}
