#!/bin/bash

{% if acme_sh_freedns_user is defined and acme_sh_freedns_password is defined %}
docker run --rm --name {{ acme_sh_hostname }}-tmp \
--volume "{{ acme_sh_data_dir }}:/acme.sh" \
--env "FREEDNS_User={{ acme_sh_freedns_user }}" \
---env "FREEDNS_Password={{ acme_sh_freedns_password }}" \
{{ acme_sh_image }} \
--renew --dns dns_freedns {% for item in acme_sh_certs %}-d {{ item.src_hostname }} {% endfor %}
{% endif %}

{% if acme_sh_vercel_token is defined %}
docker run --rm --name {{ acme_sh_hostname }}-tmp \
--volume "{{ acme_sh_data_dir }}:/acme.sh" \
--env "VERCEL_TOKEN={{ acme_sh_vercel_token }}" \
{{ acme_sh_image }} \
--renew --dns dns_vercel {% for item in acme_sh_certs %}-d {{ item.src_hostname }} {% endfor %} \
--debug
{% endif %}
