#!/usr/bin/env bash
set -e

repository='https://ansible.build'

scripts=(
    docker-mysql-backup
    docker-mysql-drop
    docker-mysql-list
    docker-mysql-restore
)

for script in "${scripts[@]}"; do
    echo "Install $script script ..."
    sudo curl -L "$repository/mysql/$script" -o "/usr/local/bin/$script"
    sudo chmod +x "/usr/local/bin/$script"
done
