#!/bin/bash

# Exit script if command fails
set -e

# Run the renew command in certbot container
docker run --rm --name {{ certbot_hostname }}-tmp \
-v "{{ certbot_data_dir }}/:/etc/letsencrypt/" \
-v "{{ certbot_data_dir }}/www/:/var/www/certbot/" \
{{ certbot_image }} \
renew
